driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://127.0.0.1:3306/achados_perdidos_iguatemi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&characterEncoding=utf8
usuario=root
senha=
